Do not rely on MW initialization order when being autoloaded.
SemanticMediaWiki/SemanticMediaWiki pull request #5136
Opened 2021-11-17 20:39 UTC by Pchelolo

Currently SMW setup uses both composer and extension.json.
During the composer autoload it executes SemanticMediaWiki.php
to export it's own constants to be used in LocalSettings.php.
Additionally it does self-check to see if it's intalled correctly.

During autoloading you can't rely on ANY part of MediaWiki to be
initialized. In this case it relied on $wgVersion and $wgLanguageCode
to be present. They will not be anymore since core is moving
dependency autoloading earlier.

In general, this pattern will be prohibited in MW 1.38 and will
be broken intentionally - relying on MW to be partially initialized
during class autoloading is a bad, bad, bad idea.

This fix is a stop-gap to avoid breaking translatewiki entirely.

Bug: https://phabricator.wikimedia.org/T295883

2021-11-18 00:30 UTC, legoktm requested changes

2021-11-18 00:30 UTC, legoktm commented on extension.json
> +		"SemanticMediaWikiAlias": "/i18n/extra/SemanticMediaWiki.alias.php",
No leading / here

2021-11-18 00:34 UTC, JeroenDeDauw commented
Perhaps it is best to just remove this whole setup check. Or at least stop running stuff via the composer autoloader.

2021-11-18 18:48 UTC, Pchelolo commented on extension.json
> +		"SemanticMediaWikiAlias": "/i18n/extra/SemanticMediaWiki.alias.php",
done

2021-11-18 18:50 UTC, Pchelolo commented
> Perhaps it is best to just remove this whole setup check. Or at least stop running stuff via the composer autoloader.

This is a minimal fix to unbreak translatewiki. I believe it will be beneficial to convert the extension to standard extension registration mechanism, but that decision is not up to me.

2021-11-18 22:14 UTC, JeroenDeDauw commented
A PR that does that is most welcome! I will definitely review it.

2021-11-18 22:18 UTC, JeroenDeDauw commented
I understand that this makes sense to unbreak translatewiki. Not clear it makes sense long term though, which is why I have not merged it yet. If it is broken anyway, then removal (or fix) seems better than putting in some dummy values to make PHP errors go away.

2021-11-22 16:02 UTC, Nikerabbit commented
This seems to work in my development environment, though currently setup only as a local hack in non-permanent way. Having it merged (or at least available in a local branch) would help greatly.

2021-11-22 16:08 UTC, merged